name: push_builder # 이름은 자유롭게 설정
 
on:
  push: # 이벤트 설정 - push 이벤트 때 동작
    branches: main # 브랜치 설정 - main 브랜치에서 push 이벤트가 일어나면 동작
 
jobs:
  deploy:
    runs-on: ubuntu-latest # 인스턴스 OS
    steps: 
    - name: Checkout source code
      uses: actions/checkout@v2 # 워크플로에서 액세스할 수 있도록 에서 저장소를 체크아웃
    
    - name: Setup node
      uses: actions/setup-node@v1 # 노드 설치
      with:
        node-version: '14'
        
    - run: npm install
    
    - name: Setup yarn
      run: npm install -g yarn
      
    - name: Install Dependencies
      run: yarn
      
    - name: Build
      run: yarn build
      env: # build 할 때 필요한 환경 변수 추가, Settings의 Secrets에서 추가 가능
        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
 
    - name: S3 Deploy
      run: aws s3 sync ./dist s3://perf-basecamp-yungo1846/ # 본인 s3 주소 입력
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
